with-expecter: true
packages:
  github.com/itohio/dndm:
    config:
      filename: "mock_{{.InterfaceName}}.go"
      dir: "{{.InterfaceDir}}"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: True
    interfaces:
      Intent:
      IntentInternal:
      Interest:
      InterestInternal:
      Endpoint:
  github.com/itohio/dndm/network:
    config:
      filename: "mock_{{.InterfaceName}}.go"
      dir: "{{.InterfaceDir}}"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: True
    interfaces:
      Conn:
      Dialer:
      Node:
      Server:
