// Code generated by mockery v2.42.3. DO NOT EDIT.

package dndm

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// MockIntent is an autogenerated mock type for the Intent type
type MockIntent struct {
	mock.Mock
}

type MockIntent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIntent) EXPECT() *MockIntent_Expecter {
	return &MockIntent_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *MockIntent) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIntent_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIntent_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIntent_Expecter) Close() *MockIntent_Close_Call {
	return &MockIntent_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIntent_Close_Call) Run(run func()) *MockIntent_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIntent_Close_Call) Return(_a0 error) *MockIntent_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntent_Close_Call) RunAndReturn(run func() error) *MockIntent_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Interest provides a mock function with given fields:
func (_m *MockIntent) Interest() <-chan Route {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Interest")
	}

	var r0 <-chan Route
	if rf, ok := ret.Get(0).(func() <-chan Route); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan Route)
		}
	}

	return r0
}

// MockIntent_Interest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Interest'
type MockIntent_Interest_Call struct {
	*mock.Call
}

// Interest is a helper method to define mock.On call
func (_e *MockIntent_Expecter) Interest() *MockIntent_Interest_Call {
	return &MockIntent_Interest_Call{Call: _e.mock.On("Interest")}
}

func (_c *MockIntent_Interest_Call) Run(run func()) *MockIntent_Interest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIntent_Interest_Call) Return(_a0 <-chan Route) *MockIntent_Interest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntent_Interest_Call) RunAndReturn(run func() <-chan Route) *MockIntent_Interest_Call {
	_c.Call.Return(run)
	return _c
}

// Route provides a mock function with given fields:
func (_m *MockIntent) Route() Route {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Route")
	}

	var r0 Route
	if rf, ok := ret.Get(0).(func() Route); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Route)
	}

	return r0
}

// MockIntent_Route_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Route'
type MockIntent_Route_Call struct {
	*mock.Call
}

// Route is a helper method to define mock.On call
func (_e *MockIntent_Expecter) Route() *MockIntent_Route_Call {
	return &MockIntent_Route_Call{Call: _e.mock.On("Route")}
}

func (_c *MockIntent_Route_Call) Run(run func()) *MockIntent_Route_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIntent_Route_Call) Return(_a0 Route) *MockIntent_Route_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntent_Route_Call) RunAndReturn(run func() Route) *MockIntent_Route_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0, _a1
func (_m *MockIntent) Send(_a0 context.Context, _a1 protoreflect.ProtoMessage) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIntent_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockIntent_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 protoreflect.ProtoMessage
func (_e *MockIntent_Expecter) Send(_a0 interface{}, _a1 interface{}) *MockIntent_Send_Call {
	return &MockIntent_Send_Call{Call: _e.mock.On("Send", _a0, _a1)}
}

func (_c *MockIntent_Send_Call) Run(run func(_a0 context.Context, _a1 protoreflect.ProtoMessage)) *MockIntent_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protoreflect.ProtoMessage))
	})
	return _c
}

func (_c *MockIntent_Send_Call) Return(_a0 error) *MockIntent_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntent_Send_Call) RunAndReturn(run func(context.Context, protoreflect.ProtoMessage) error) *MockIntent_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIntent creates a new instance of MockIntent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIntent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIntent {
	mock := &MockIntent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
