// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: types/core/interests.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Interests is the message that contains a list of interests
type Interests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interests     []*Interest            `protobuf:"bytes,1,rep,name=interests,proto3" json:"interests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interests) Reset() {
	*x = Interests{}
	mi := &file_types_core_interests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interests) ProtoMessage() {}

func (x *Interests) ProtoReflect() protoreflect.Message {
	mi := &file_types_core_interests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interests.ProtoReflect.Descriptor instead.
func (*Interests) Descriptor() ([]byte, []int) {
	return file_types_core_interests_proto_rawDescGZIP(), []int{0}
}

func (x *Interests) GetInterests() []*Interest {
	if x != nil {
		return x.Interests
	}
	return nil
}

// Interest is the message for advertising interest in certain type of data
type Interest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         string                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Hops          uint64                 `protobuf:"varint,2,opt,name=hops,proto3" json:"hops,omitempty"`
	Ttl           uint64                 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Register      bool                   `protobuf:"varint,4,opt,name=register,proto3" json:"register,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interest) Reset() {
	*x = Interest{}
	mi := &file_types_core_interests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interest) ProtoMessage() {}

func (x *Interest) ProtoReflect() protoreflect.Message {
	mi := &file_types_core_interests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interest.ProtoReflect.Descriptor instead.
func (*Interest) Descriptor() ([]byte, []int) {
	return file_types_core_interests_proto_rawDescGZIP(), []int{1}
}

func (x *Interest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Interest) GetHops() uint64 {
	if x != nil {
		return x.Hops
	}
	return 0
}

func (x *Interest) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Interest) GetRegister() bool {
	if x != nil {
		return x.Register
	}
	return false
}

var File_types_core_interests_proto protoreflect.FileDescriptor

var file_types_core_interests_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x3f, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x65, 0x73, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x52, 0x09,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x22, 0x62, 0x0a, 0x08, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x6f, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x68, 0x6f, 0x70, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x74, 0x74,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x42, 0x8c, 0x01,
	0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x42, 0x0e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x74, 0x6f, 0x68, 0x69, 0x6f, 0x2f, 0x64, 0x6e, 0x64, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0xa2, 0x02, 0x03, 0x54, 0x43, 0x58, 0xaa, 0x02, 0x0a, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x72, 0x65, 0xca, 0x02, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x5c, 0x43, 0x6f, 0x72, 0x65, 0xe2, 0x02, 0x16, 0x54, 0x79, 0x70, 0x65, 0x73, 0x5c, 0x43, 0x6f,
	0x72, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x0b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x3a, 0x3a, 0x43, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_types_core_interests_proto_rawDescOnce sync.Once
	file_types_core_interests_proto_rawDescData []byte
)

func file_types_core_interests_proto_rawDescGZIP() []byte {
	file_types_core_interests_proto_rawDescOnce.Do(func() {
		file_types_core_interests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_core_interests_proto_rawDesc), len(file_types_core_interests_proto_rawDesc)))
	})
	return file_types_core_interests_proto_rawDescData
}

var file_types_core_interests_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_core_interests_proto_goTypes = []any{
	(*Interests)(nil), // 0: types.core.Interests
	(*Interest)(nil),  // 1: types.core.Interest
}
var file_types_core_interests_proto_depIdxs = []int32{
	1, // 0: types.core.Interests.interests:type_name -> types.core.Interest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_types_core_interests_proto_init() }
func file_types_core_interests_proto_init() {
	if File_types_core_interests_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_core_interests_proto_rawDesc), len(file_types_core_interests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_core_interests_proto_goTypes,
		DependencyIndexes: file_types_core_interests_proto_depIdxs,
		MessageInfos:      file_types_core_interests_proto_msgTypes,
	}.Build()
	File_types_core_interests_proto = out.File
	file_types_core_interests_proto_goTypes = nil
	file_types_core_interests_proto_depIdxs = nil
}
